Add Permutation
NASU41/AtCoderLibraryForJava pull request #44
Opened 2020-09-21 16:06 UTC by m1kit

2020-09-23 16:04 UTC, uwi commented
`Iterable<int[]>`も`implements`したほうが使いやすい気がします。
[参考](https://qiita.com/Hiro256/items/9768f3f9b47ae01898e1)

2020-09-24 06:45 UTC, uwi requested changes
自分で実装していて気づいたんですが、拡張`for`だと最初も`next()`が呼ばれるらしく、最初のpermutationが欠けてしまいますね。`first`フラグを導入するか、`next`の初期値を別な値にするかぐらいですかね・・

2020-09-24 07:41 UTC, m1kit commented
> 自分で実装していて気づいたんですが、拡張`for`だと最初も`next()`が呼ばれるらしく、最初のpermutationが欠けてしまいますね。`first`フラグを導入するか、`next`の初期値を別な値にするかぐらいですかね・・

```java
public class Main {
  public static void main(String...args) {
    Permutation perm = new Permutation(3);
    outer:
    for (int[] p : perm) {
      System.out.println(java.util.Arrays.toString(p));
    }
  }
}
```
これで
```
[0, 1, 2]
[0, 2, 1]
[1, 0, 2]
[1, 2, 0]
[2, 0, 1]
[2, 1, 0]
```
これが出てくるので，問題ないと思っているのですが，再現するコードを教えていただけますか？

2020-09-24 07:56 UTC, uwi commented
あ、理解しました。`nextPermutation`で返すものは、そこで返すんではなく次に返すんですね

2020-09-24 07:56 UTC, uwi approved these changes

2020-09-25 03:21 UTC, merged